# =================================
# SERVICE CONFIGURATION
# =================================
server:
  port: 9000

# =======================================
# Enables Spring Boot Actuator end points
# =======================================
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: "ALWAYS"

# =======================================
# Enables Eureka client 
# =======================================
spring:
  cloud:
    config:
      enabled: true
      uri: http://localhost:9999
